# 안녕하세요^^ 
# AIVLE 미니 프로젝트에 오신 여러분을 환영합니다.
* 본 과정에서는 실제 사례와 데이터를 기반으로 문제를 해결하는 전체 과정을 자기 주도형 실습으로 진행해볼 예정입니다.
* 앞선 교육과정을 정리하는 마음과 지금까지 배운 내용을 바탕으로 문제 해결을 해볼게요!
* 미니 프로젝트를 통한 문제 해결 과정 'A에서 Z까지', 지금부터 시작합니다!

---

In [11]:
# 필요 라이브러리부터 설치할께요.
!pip install pandas seaborn

Requirement already satisfied: pandas in c:\users\user\anaconda3\lib\site-packages (1.2.4)
Requirement already satisfied: seaborn in c:\users\user\anaconda3\lib\site-packages (0.11.1)
Requirement already satisfied: numpy>=1.16.5 in c:\users\user\anaconda3\lib\site-packages (from pandas) (1.20.1)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\user\anaconda3\lib\site-packages (from pandas) (2.8.1)
Requirement already satisfied: pytz>=2017.3 in c:\users\user\anaconda3\lib\site-packages (from pandas) (2021.1)
Requirement already satisfied: six>=1.5 in c:\users\user\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)
Requirement already satisfied: matplotlib>=2.2 in c:\users\user\anaconda3\lib\site-packages (from seaborn) (3.3.4)
Requirement already satisfied: scipy>=1.0 in c:\users\user\anaconda3\lib\site-packages (from seaborn) (1.6.2)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (1.3.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (2.4.7)
Requirement already satisfied: cycler>=0.10 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (0.10.0)
Requirement already satisfied: pillow>=6.2.0 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (8.2.0)

---

# (실습준비) 데이터 불러오기부터

In [12]:
import numpy as np
import pandas as pd

In [13]:
# 학습 데이터 로딩
air_21 = pd.read_csv("air_2021.csv", sep=',', index_col = 0, encoding = 'utf-8' )
air_22 = pd.read_csv("air_2022.csv", sep=',', index_col = 0, encoding = 'utf-8' )
weather_21 = pd.read_csv("weather_2021.csv", sep = ',', encoding='cp949')
weather_22 = pd.read_csv("weather_2022.csv", sep = ',', encoding='cp949')

---

# 1. 이상치/결측치 처리

#### [실습문제1] 미세먼지 데이터 결측치 처리
* 미세먼지 데이터의 결측치를 확인하고 결측치가 존재한다면 처리해주세요.


* 앞서 데이터 불러오기 및 분석 단계에서 확인한 불필요한 변수에 대해 제거 해 주세요.

In [14]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
col = ['지역', '망', '측정소코드', '측정소명', '주소']

air_21 = air_21.drop(col, axis=1)
air_22 = air_22.drop(col, axis=1)

In [15]:
air_21.isna().sum() # 전체 8760 행

측정일시      0
SO2     112
CO       80
O3       97
NO2      80
PM10    105
PM25     97
dtype: int64

In [16]:
air_22.isna().sum() # 전체 2159 행

측정일시     0
SO2     21
CO      21
O3      21
NO2     21
PM10    38
PM25    25
dtype: int64

- NaN 값 처리

In [17]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

In [18]:
col_name = list(air_21)

In [19]:
imputer = IterativeImputer()
air_21 = imputer.fit_transform(air_21)
air_22 = imputer.fit_transform(air_22) # test 데이터이므로 따로 설정

In [20]:
air_21= pd.DataFrame(air_21)
air_22 = pd.DataFrame(air_22)

In [21]:
air_21.columns = col_name
air_22.columns = col_name

In [22]:
air_21.head()

           측정일시    SO2   CO     O3    NO2  PM10  PM25
0  2.021100e+09  0.003  0.6  0.002  0.039  31.0  18.0
1  2.021100e+09  0.003  0.6  0.002  0.035  27.0  16.0
2  2.021100e+09  0.003  0.6  0.002  0.033  28.0  18.0
3  2.021100e+09  0.003  0.6  0.002  0.030  26.0  16.0
4  2.021100e+09  0.003  0.5  0.003  0.026  26.0  16.0

#### [실습문제2] 날씨 데이터 결측치 처리
* 날씨 데이터의 결측치를 확인하고 결측치가 존재한다면 처리해주세요.

* '강우량'을 어떻게 해야할까요?

In [23]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
col = ['지점', '지점명', '기온 QC플래그', '강수량 QC플래그', '풍속 QC플래그', '풍향 QC플래그', '습도 QC플래그', '현지기압 QC플래그', '해면기압 QC플래그', '3시간신적설(cm)', '지면상태(지면상태코드)', '지면온도 QC플래그', '현상번호(국내식)', '일조 QC플래그', '일사 QC플래그', '운형(운형약어)']

weather_21 = weather_21.drop(col, axis=1)
weather_22 = weather_22.drop(col, axis=1)

In [24]:
weather_21.isna().sum() # 전체 8759행

일시                  0
기온(°C)              0
강수량(mm)          7810
풍속(m/s)             2
풍향(16방위)            2
습도(%)               0
증기압(hPa)            0
이슬점온도(°C)           0
현지기압(hPa)           0
해면기압(hPa)           0
일조(hr)           3968
일사(MJ/m2)        3968
적설(cm)           8380
전운량(10분위)           2
중하층운량(10분위)         0
최저운고(100m )      4212
시정(10m)             0
지면온도(°C)            5
5cm 지중온도(°C)        5
10cm 지중온도(°C)       5
20cm 지중온도(°C)       5
30cm 지중온도(°C)       5
dtype: int64

In [25]:
weather_22.isna().sum() # 전체 2159행

일시                  0
기온(°C)              0
강수량(mm)          2079
풍속(m/s)             0
풍향(16방위)            0
습도(%)               0
증기압(hPa)            0
이슬점온도(°C)           0
현지기압(hPa)           0
해면기압(hPa)           0
일조(hr)           1089
일사(MJ/m2)        1089
적설(cm)           2020
전운량(10분위)           0
중하층운량(10분위)         0
최저운고(100m )      1417
시정(10m)             0
지면온도(°C)            0
5cm 지중온도(°C)        0
10cm 지중온도(°C)       0
20cm 지중온도(°C)       0
30cm 지중온도(°C)       0
dtype: int64

In [26]:
na_cols = ['강수량(mm)', '적설(cm)']
weather_21 = weather_21.drop(na_cols, axis=1)
weather_22 = weather_22.drop(na_cols, axis=1)

- NaN 값 처리

In [27]:
col_name = list(weather_21)

In [28]:
day_21 = weather_21.loc[:, ['일시']]
day_22 = weather_22.loc[:, ['일시']]

In [29]:
tmp_21 = weather_21.drop('일시', axis=1)
tmp_22 = weather_22.drop('일시', axis=1)

In [30]:
imputer = IterativeImputer()
tmp_21 = imputer.fit_transform(tmp_21)
tmp_22 = imputer.fit_transform(tmp_22) # test 데이터이므로 따로 설정

In [31]:
tmp_21 = pd.DataFrame(tmp_21)
tmp_22 = pd.DataFrame(tmp_22)

In [32]:
weather_21 = pd.concat([day_21, tmp_21], axis=1)
weather_22 = pd.concat([day_22, tmp_22], axis=1)

In [33]:
weather_21.columns = col_name
weather_22.columns = col_name

In [34]:
weather_22.head()

,일시,기온(°C),풍속(m/s),풍향(16방위),습도(%),증기압(hPa),이슬점온도(°C),현지기압(hPa),해면기압(hPa),일조(hr),일사(MJ/m2),전운량(10분위),중하층운량(10분위),최저운고(100m ),시정(10m),지면온도(°C),5cm 지중온도(°C),10cm 지중온도(°C),20cm 지중온도(°C),30cm 지중온도(°C)
0,2022-01-01 00:00,-8.5,1.9,320.0,41.0,1.3,-19.4,1021.9,1033.2,0.750029,0.465916,0.0,0.0,23.311443,2000.0,-7.0,-1.0,-1.0,-0.2,1.0
1,2022-01-01 01:00,-9.2,1.8,270.0,42.0,1.3,-19.7,1022.2,1033.6,0.749782,0.474902,0.0,0.0,22.736786,2000.0,-7.2,-1.1,-1.1,-0.2,1.0
2,2022-01-01 02:00,-9.5,1.2,270.0,43.0,1.3,-19.7,1022.3,1033.7,0.743924,0.423831,0.0,0.0,23.020726,2000.0,-7.5,-1.3,-1.2,-0.2,1.0
3,2022-01-01 03:00,-9.3,1.4,290.0,46.0,1.4,-18.8,1022.6,1034.0,0.735180,0.386251,0.0,0.0,22.034066,2000.0,-7.6,-1.4,-1.2,-0.2,1.0
4,2022-01-01 04:00,-9.6,1.7,340.0,48.0,1.4,-18.5,1021.9,1033.3,0.737382,0.444682,0.0,0.0,20.980363,2000.0,-7.6,-1.4,-1.3,-0.3,1.0

#### [실습문제3] air_21, air_22 의 '측정일시'를 활용하여 'time'변수 생성하기


* air_21, air_22 의 '측정일시'를 활용하여 'time'변수 생성


* time 변수를 datatime으로 데이터 타입 변경하기

In [36]:
# 1일 24시 = 2일 0시로 데이터가 설정되어 있어서 24 -> 0으로 바꾸면 시간대 오류 발생
air_21['time'] = air_21['측정일시'] - 1
air_22['time'] = air_22['측정일시'] - 1

air_21['time'] = pd.to_datetime(air_21['time'],format='%Y%m%d%H')
air_22['time'] = pd.to_datetime(air_22['time'],format='%Y%m%d%H')

In [37]:
import datetime

air_21['time']= air_21['time'] + datetime.timedelta(hours=1)
air_22['time']= air_22['time'] + datetime.timedelta(hours=1)

In [38]:
air_21.drop('측정일시', axis=1, inplace=True)
air_22.drop('측정일시', axis=1, inplace=True)

#### [실습문제4] weather_21, weather_22 의 '일시'를 활용하여 'time'변수 생성하기


* weather_21, weather_22 의 '측정일시'를 활용하여 'time'변수 생성


* time 변수를 datatime으로 데이터 타입 변경하기

In [39]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
weather_21['time'] = pd.to_datetime(weather_21['일시'])
weather_22['time'] = pd.to_datetime(weather_22['일시'])

In [40]:
weather_21.drop('일시', axis=1, inplace=True)
weather_22.drop('일시', axis=1, inplace=True)

---

# 2. 데이터 합치기
* 미세먼지 데이터와 날씨 데이터를 'time' 기준으로 합쳐보겠습니다

#### [실습문제5] 데이터 합치기
* 'df_21','df_22'에 21년도와 22년도의 미세먼지, 날씨 데이터를 합쳐 넣도록 하겠습니다.

In [52]:
# 아래에 실습코드를 작성하고 결과를 확인합니다
df_21 = pd.merge(air_21, weather_21, how='inner', on='time')
df_22 = pd.merge(air_22, weather_22, how='inner', on='time')

In [53]:
df_21 = df_21.drop('time', axis=1)
df_22 = df_22.drop('time', axis=1)

In [54]:
df_21.head()

,SO2,CO,O3,NO2,PM10,PM25,기온(°C),풍속(m/s),풍향(16방위),습도(%),...,일사(MJ/m2),전운량(10분위),중하층운량(10분위),최저운고(100m ),시정(10m),지면온도(°C),5cm 지중온도(°C),10cm 지중온도(°C),20cm 지중온도(°C),30cm 지중온도(°C)
0,0.003,0.6,0.002,0.039,31.0,18.0,18.7,1.0,20.0,85.0,...,0.073400,0.0,0.0,18.272729,2000.0,17.4,22.1,22.0,22.5,22.9
1,0.003,0.6,0.002,0.035,27.0,16.0,18.3,0.3,0.0,89.0,...,-0.035511,0.0,0.0,18.395455,2000.0,17.2,21.8,21.8,22.4,22.8
2,0.003,0.6,0.002,0.033,28.0,18.0,17.7,2.0,20.0,92.0,...,0.152019,0.0,0.0,12.608914,2000.0,17.0,21.6,21.6,22.2,22.8
3,0.003,0.6,0.002,0.030,26.0,16.0,17.4,1.0,50.0,91.0,...,0.043380,0.0,0.0,13.938493,2000.0,16.5,21.3,21.4,22.0,22.7
4,0.003,0.5,0.003,0.026,26.0,16.0,17.2,1.3,270.0,94.0,...,-0.095500,4.0,0.0,12.403328,1995.0,16.6,21.1,21.2,21.9,22.6

#### [실습문제6] 각종 인자 추가 및 사용하지 않을 변수 제거

* 새로운 인자를 추가 하세요.


* 머신러닝에 사용하지 않을 변수들을 제거해줍니다.

In [55]:
df_21.corr()

,SO2,CO,O3,NO2,PM10,PM25,기온(°C),풍속(m/s),풍향(16방위),습도(%),...,일사(MJ/m2),전운량(10분위),중하층운량(10분위),최저운고(100m ),시정(10m),지면온도(°C),5cm 지중온도(°C),10cm 지중온도(°C),20cm 지중온도(°C),30cm 지중온도(°C)
SO2,1.000000,0.338577,0.110043,0.328963,0.216358,0.378685,0.050957,-0.040564,0.045864,-0.161695,...,0.113111,0.018814,-0.015277,0.049876,-0.097618,0.010383,-0.068376,-0.085933,-0.110746,-0.131897
CO,0.338577,1.000000,-0.464090,0.866905,0.310959,0.638300,-0.392717,-0.288745,-0.090189,0.064074,...,-0.186794,-0.049630,-0.059421,0.031688,-0.318025,-0.457786,-0.498627,-0.499716,-0.502675,-0.505637
O3,0.110043,-0.464090,1.000000,-0.579223,-0.027176,-0.085493,0.498686,0.323578,0.255235,-0.308562,...,0.423187,0.029066,-0.007814,0.011024,0.156071,0.551199,0.482001,0.454978,0.413519,0.382675
NO2,0.328963,0.866905,-0.579223,1.000000,0.241285,0.516793,-0.317118,-0.380294,-0.165730,0.046041,...,-0.241789,-0.011313,-0.035620,0.104343,-0.211199,-0.408044,-0.422953,-0.421219,-0.421309,-0.424581
PM10,0.216358,0.310959,-0.027176,0.241285,1.000000,0.674728,-0.126319,0.011480,0.098917,-0.066195,...,0.007290,-0.100509,-0.090529,-0.004256,-0.349206,-0.139272,-0.175424,-0.182834,-0.194090,-0.206874
PM25,0.378685,0.638300,-0.085493,0.516793,0.674728,1.000000,-0.176069,-0.134776,0.084119,-0.001662,...,-0.065942,-0.045246,-0.077530,0.019282,-0.509480,-0.223565,-0.274478,-0.283068,-0.298015,-0.313803
기온(°C),0.050957,-0.392717,0.498686,-0.317118,-0.126319,-0.176069,1.000000,-0.069386,-0.181563,0.145404,...,0.248086,0.307396,0.153382,0.067203,0.068418,0.946631,0.950930,0.938375,0.917655,0.901833
풍속(m/s),-0.040564,-0.288745,0.323578,-0.380294,0.011480,-0.134776,-0.069386,1.000000,0.172828,-0.285262,...,0.305828,-0.026951,0.036420,-0.138432,0.106376,0.014738,-0.067953,-0.082376,-0.102395,-0.111888
풍향(16방위),0.045864,-0.090189,0.255235,-0.165730,0.098917,0.084119,-0.181563,0.172828,1.000000,-0.200957,...,0.062314,-0.176883,-0.095107,-0.056081,0.025555,-0.138333,-0.147261,-0.153715,-0.166019,-0.175748
습도(%),-0.161695,0.064074,-0.308562,0.046041,-0.066195,-0.001662,0.145404,-0.285262,-0.200957,1.000000,...,-0.477817,0.362260,0.379977,-0.333231,-0.501758,0.055285,0.220927,0.248033,0.283351,0.303444
증기압(hPa),-0.059275,-0.391505,0.321507,-0.335675,-0.203987,-0.227620,0.881615,-0.147426,-0.189101,0.450867,...,0.054106,0.356747,0.239803,-0.090676,-0.038048,0.830569,0.912108,0.914764,0.914936,0.913457
이슬점온도(°C),-0.019062,-0.322513,0.316891,-0.261301,-0.138909,-0.157768,0.926402,-0.169204,-0.231957,0.501853,...,0.029445,0.397714,0.269643,-0.056779,-0.108015,0.845957,0.917294,0.917568,0.914056,0.908510
현지기압(hPa),-0.022372,0.341200,-0.396682,0.344254,0.022030,0.156683,-0.680025,-0.046215,0.044046,-0.359807,...,-0.059753,-0.358469,-0.306983,0.198683,0.140369,-0.646085,-0.703643,-0.699816,-0.692677,-0.682956
해면기압(hPa),-0.024242,0.349145,-0.407853,0.348071,0.027577,0.160056,-0.707822,-0.040781,0.052269,-0.354960,...,-0.069938,-0.361961,-0.304160,0.187568,0.132208,-0.672054,-0.727868,-0.723543,-0.715607,-0.705416
일조(hr),0.076104,-0.037407,0.185565,-0.090342,0.056814,0.001941,-0.077906,0.200000,0.127281,-0.557107,...,0.678186,-0.684725,-0.607805,0.165193,0.285957,0.073174,-0.136697,-0.158170,-0.177855,-0.178144
일사(MJ/m2),0.113111,-0.186794,0.423187,-0.241789,0.007290,-0.065942,0.248086,0.305828,0.062314,-0.477817,...,1.000000,-0.184615,-0.181964,-0.189812,0.214846,0.476893,0.139841,0.098423,0.057912,0.054584
전운량(10분위),0.018814,-0.049630,0.029066,-0.011313,-0.100509,-0.045246,0.307396,-0.026951,-0.176883,0.362260,...,-0.184615,1.000000,0.748747,-0.142178,-0.240841,0.248052,0.267249,0.265079,0.260144,0.256753
중하층운량(10분위),-0.015277,-0.059421,-0.007814,-0.035620,-0.090529,-0.077530,0.153382,0.036420,-0.095107,0.379977,...,-0.181964,0.748747,1.000000,-0.212554,-0.271131,0.115251,0.133352,0.133328,0.132729,0.133827
최저운고(100m ),0.049876,0.031688,0.011024,0.104343,-0.004256,0.019282,0.067203,-0.138432,-0.056081,-0.333231,...,-0.189812,-0.142178,-0.212554,1.000000,0.303999,-0.019916,0.061767,0.068798,0.071247,0.059257
시정(10m),-0.097618,-0.318025,0.156071,-0.211199,-0.349206,-0.509480,0.068418,0.106376,0.025555,-0.501758,...,0.214846,-0.240841,-0.271131,0.303999,1.000000,0.110849,0.096763,0.093511,0.090930,0.093593
지면온도(°C),0.010383,-0.457786,0.551199,-0.408044,-0.139272,-0.223565,0.946631,0.014738,-0.138333,0.055285,...,0.476893,0.248052,0.115251,-0.019916,0.110849,1.000000,0.917000,0.898344,0.875287,0.865601
5cm 지중온도(°C),-0.068376,-0.498627,0.482001,-0.422953,-0.175424,-0.274478,0.950930,-0.067953,-0.147261,0.220927,...,0.139841,0.267249,0.133352,0.061767,0.096763,0.917000,1.000000,0.998379,0.991310,0.982873
10cm 지중온도(°C),-0.085933,-0.499716,0.454978,-0.421219,-0.182834,-0.283068,0.938375,-0.082376,-0.153715,0.248033,...,0.098423,0.265079,0.133328,0.068798,0.093511,0.898344,0.998379,1.000000,0.996930,0.990546
20cm 지중온도(°C),-0.110746,-0.502675,0.413519,-0.421309,-0.194090,-0.298015,0.917655,-0.102395,-0.166019,0.283351,...,0.057912,0.260144,0.132729,0.071247,0.090930,0.875287,0.991310,0.996930,1.000000,0.997712
30cm 지중온도(°C),-0.131897,-0.505637,0.382675,-0.424581,-0.206874,-0.313803,0.901833,-0.111888,-0.175748,0.303444,...,0.054584,0.256753,0.133827,0.059257,0.093593,0.865601,0.982873,0.990546,0.997712,1.000000

In [56]:
# 아래에 실습코드를 작성하고 결과를 확인합니다
p_less_1p = ['O3', '풍속(m/s)', '풍향(16방위)', '습도(%)', '현지기압(hPa)', '해면기압(hPa)', '일조(hr)', '일사(MJ/m2)', '중하층운량(10분위)', '최저운고(100m )']

In [57]:
# 아래에 실습코드를 작성하고 결과를 확인합니다
df_21 = df_21.drop(p_less_1p, axis=1)
df_22 = df_22.drop(p_less_1p, axis=1)

#### [실습문제7] 미세먼지 농도 다음시점 데이터 생성

* t+1 시점 데이터 생성

In [58]:
# 아래에 실습코드를 작성하고 결과를 확인합니다
df_21['PM10_lag1'] = df_21['PM10'].shift(-1)
df_22['PM10_lag1'] = df_22['PM10'].shift(-1)

In [59]:
df_21.head()

,SO2,CO,NO2,PM10,PM25,기온(°C),증기압(hPa),이슬점온도(°C),전운량(10분위),시정(10m),지면온도(°C),5cm 지중온도(°C),10cm 지중온도(°C),20cm 지중온도(°C),30cm 지중온도(°C),PM10_lag1
0,0.003,0.6,0.039,31.0,18.0,18.7,18.3,16.1,0.0,2000.0,17.4,22.1,22.0,22.5,22.9,27.0
1,0.003,0.6,0.035,27.0,16.0,18.3,18.6,16.4,0.0,2000.0,17.2,21.8,21.8,22.4,22.8,28.0
2,0.003,0.6,0.033,28.0,18.0,17.7,18.5,16.3,0.0,2000.0,17.0,21.6,21.6,22.2,22.8,26.0
3,0.003,0.6,0.030,26.0,16.0,17.4,18.1,15.9,0.0,2000.0,16.5,21.3,21.4,22.0,22.7,26.0
4,0.003,0.5,0.026,26.0,16.0,17.2,18.4,16.2,4.0,1995.0,16.6,21.1,21.2,21.9,22.6,22.0

In [60]:
l_21 = df_21.shape[0] - 1
l_22 = df_22.shape[0] - 1

In [61]:
df_21 = df_21.drop(l_21, axis=0)
df_22 = df_22.drop(l_22, axis=0)

---

# 3. train / test split

#### [실습문제7] 데이터셋 나누기 

* 데이터셋을 train(21년도 데이터), test(22년도 데이터)로 나눠 csv로 저장하도록 하겠습니다.


* train_x / train_y / test_x / test_y 로 나누세요.


* train_x.csv / train_y.csv / test_x.csv / test_y.csv 로 저장하세요.

In [62]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
train_x = df_21.drop('PM10_lag1', axis=1)
train_y = df_21['PM10_lag1']

test_x = df_22.drop('PM10_lag1', axis=1)
test_y = df_22['PM10_lag1']

In [63]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
train_x.to_csv('train_x.csv', index=False)
train_y.to_csv('train_y.csv', index=False)

test_x.to_csv('test_x.csv', index=False)
test_y.to_csv('test_y.csv', index=False)

---